
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    defer-datasource-initialization: true  # Ensures JPA runs before data.sql
  sql:
    init:
      mode: always  # Ensures data.sql runs after JPA
      data-locations: classpath:data.sql  # Specifies the location of the script

  h2:
    console:
      enabled: true
      path: /h2-console  # H2 web console path
