
server:
  port: 8081
  
spring:
  application:
    name: task2
  datasource:
    username: root
    password: jadoo1838
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zest

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
